### ISSUE TITLE
Misunderstanding of bitwise operator in big int validation

### ISSUE THREAD

**Issue by mrhn** [Rackbeat/laravel-validate-mysql-integers#1]
In BigInteger rule-following is used `return 2 ^ 63 - 1;`, this will evaluate to 60. This was probably meant as mathetics version of power, the ^ sign is not defined in PHP or any other language as power and Math.power should be used. Will do a pr tonight.

[Documentation](http://php.net/manual/en/language.operators.bitwise.php)

**Comment by jstoone** [comment]
In PHP 5.6 the `**`-operator was introduced as a stand-in for `pow()`.

So the statment should look something in the lines of: `2 ** 63 - 1`.

**Comment by LasseRafn** [comment]
Interesting! I can't believe I didn't know of this. I actually thought that my tests covered this.. huh. Maybe the tests needs to be revised.

Are any of you working on a PR? Otherwise I will fix it right away 👍 

Thanks!!

**Comment by jstoone** [comment]
@LasseRafn your tests definitely work, but they're passing because the assertions are using the same calculations.

I forked and played around with the tests yesterday, and ended up correcting the tests and the class itself. So I'll have a PR ready in a few hours. ✌️

**Comment by LasseRafn** [comment]
Makes sense! Totally skipped that part. Thanks!

**Comment by LasseRafn** [comment]
Good job! Thanks for this! 👍  **VERY** appreciated

**Comment by LasseRafn** [comment]
Tagged v1.3
